baseURL = "https://ablyblog.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Ably Blog"

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

########################### Navigation ###################################

[[menu.main]]
URL = "tools"
name = "tools"
weight = 1

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2


[[menu.Footer]]
URL = "contact"
name = "Contact"
weight = 1

#[params.staticman]
    # If using GitHub, go to https://github.com/apps/staticman-net
    # If using GitLab, just add the GitLab bot, NO need to hit `/connect/v3/...`
    enabled             = false
    api                 = ""  # without trailing slash, defaults to "staticman3.herokuapp.com"
    gitProvider         = "github"  # either "github" or "gitlab"
    username            = "ably85"
    repo                = "northendlab-hugo"
    branch              = "master"

#[params.staticman.recaptcha]
      # Both keys must be present to enable recaptcha
      siteKey           = "" # Site Key
      encryptedKey      = ""

######################### Default Parameters ###########################
[params]
author = "Ably"
contact_form_action = ""
copyright = "&copy; 2020 Ably Blog All Rights Reserved"
description = "This is meta description"
google_analitycs_id = "UA-164118899-1"
#google_tag_manager = "GTM-KQGF6ZC"
home = "Blog"
logo = "images/loho2.svg"

# preloader
[params.preloader]
enable = true
preloader = ""

# search
[params.search]
enable = true

####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/illustration.svg"
title = "Salut! Je suis Ali, et sa c'est mon Blog!"

######################## call to action ###############################
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

############################## Social Site ##########################
[[params.social]]
icon = "ti-github"
link = "https://github.com/ably85/northendlab-hugo"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/abdelali-lyoussefi-a5413ab5/"
